<a href="https://colab.research.google.com/github/Akashgola123/Satch_neorus_network/blob/main/scatch_nerual_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
np.random.seed(0)


In [ ]:
x = 10 * np.random.rand(100,2) #generate 100 random value between 0 and 2
y = 4+3*x+np.random.rand(100,1) # linear relationship with noise

In [ ]:
# add bias term to x
x_b = np.c_[np.ones((100,1)), x]


In [ ]:
# set learning rate and nukmmber of bias
lr = 0.1 # learning rate
echo_l = int(25) #echo

In [ ]:
# initialze random weight
theta = np.random.randn(2,1)


In [ ]:
# batch gradient descent

for iteration in range(echo_l):
  gradient = 2/100*x_b.T.dot(x_b.dot(theta) - y) # compute gradient
  theta = theta - lr*gradient #update weight
  print(theta)

[[ 3.3011494   3.26408221]
 [13.42082442 13.96187936]]
[[ -6.2332795   -6.81161534]
 [-54.10793976 -56.30908935]]
[[ 49.99354476  51.57518883]
 [301.53531698 313.92182059]]
[[ -241.31687754  -251.80115467]
 [-1577.16192961 -1641.69683423]]
[[1302.10775363 1354.7066754 ]
 [8341.71934864 8683.43423441]]
[[ -6842.32446787  -7123.40378337]
 [-44031.70462526 -45834.93547903]]
[[ 36165.79417301  37646.00653118]
 [232504.27240321 242026.64857126]]
[[ -190916.72359956  -198736.83235977]
 [-1227632.9667343  -1277910.80166294]]
[[1008105.04519645 1049391.02235766]
 [6482031.3576627  6747504.46420353]]
[[ -5322841.13433543  -5540840.48833115]
 [-34225738.02551249 -35627460.16868626]]
[[2.81051671e+07 2.92562188e+07]
 [1.80715197e+08 1.88116426e+08]]
[[-1.48397926e+08 -1.54475596e+08]
 [-9.54193602e+08 -9.93272802e+08]]
[[7.83555377e+08 8.15646051e+08]
 [5.03823396e+09 5.24457589e+09]]
[[-4.13724765e+09 -4.30668950e+09]
 [-2.66023596e+10 -2.76918648e+10]]
[[2.18450654e+10 2.27397346e+10]
 [1.40463

In [ ]:
print(x_b.shape)
print(theta.shape)
print(y.shape)

(100, 2)
(3, 1)
(100, 2)
